### ISSUE TITLE
Convection allows attempting to converge when only Conditions/Metadata/Outputs of a stack have been updated

### ISSUE THREAD

**Issue by erran-r7** [rapid7/convection#140]
[Outputs documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) states the following:

> ## Important
>
> During a stack update, you cannot update outputs by themselves. You can update outputs only when you include changes that add, modify, or delete resources.

---

This generates the following stack trace:

```
ecarey@AUS-MBP-1083 ~/r/b/example-cloud (master)> convection converge vpc
    converge  Stack vpc
       error  Error converging stack vpc
* No updates are to be performed.
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/request.rb:70:in `send_request'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/convection-0.2.31/lib/convection/control/stack.rb:206:in `apply'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/convection-0.2.31/lib/convection/control/cloud.rb:30:in `block in converge'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/convection-0.2.31/lib/convection/control/cloud.rb:28:in `each'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/convection-0.2.31/lib/convection/control/cloud.rb:28:in `converge'
    /Users/ecarey/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/convection-0.2.31/bin/convection:20:in `converge'
... TRUNCATED ...
```

**Comment by erran-r7** [comment]
[Metadata](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html) has the same restriction.

**Comment by erran-r7** [comment]
[Conditions](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html) have the same restriction.
