### ISSUE TITLE
Undefined method error #message for String

### ISSUE THREAD

**Issue by erran-r7** [rapid7/convection#223]
# Description
When the AWS API request expires a undefined method error is raised.

```
us-east-1        error  Error(s) during stack initialization Request has expired., The security token included in the request is expired, The security token included in the request is expired
/Users/ecarey/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/convection-1.0.0.pre.beta.9/bin/convection:200:in block in emit_events': undefined methodmessage' for "Request has expired.":String (NoMethodError)
```

**Comment by fmitchell-r7** [comment]
I ran into this same issue while running `converge`. This is in v1.0.2.
```
For easier reading when using multiple cloudfiles output can be delayed until task completion.
If you would like delayed output please use the "--delayed_output true" option.
us-east-1        error  Error(s) during stack initialization Rate exceeded
bundler: failed to load command: convection (/Users/fmitchell/.rbenv/versions/2.3.1/bin/convection)
NoMethodError: undefined method `message' for "Rate exceeded":String
  /Users/fmitchell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/convection-1.0.2/bin/convection:200:in `block in emit_events'
  /Users/fmitchell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/convection-1.0.2/bin/convection:199:in `each'
  /Users/fmitchell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/convection-1.0.2/bin/convection:199:in `emit_events'
  /Users/fmitchell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/convection-1.0.2/bin/convection:125:in `block (3 levels) in operation'
  /Users/fmitchell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/convection-1.0.2/lib/convection/control/cloud.rb:159:in `stack_initialization_errors?'
  /Users/fmitchell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/convection-1.0.2/lib/convection/control/cloud.rb:73:in `converge'
  /Users/fmitchell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/convection-1.0.2/bin/convection:121:in `block (2 levels) in operation'
```
